name: Continuous Integration

on: [pull_request, push] # Eventos que irão disparar o workflow

jobs: # Define os jobs a serem executados
  continuous-integration: # Nome do job
    runs-on: ubuntu-latest # Define o ambiente onde o job será executado
    strategy:
      matrix:
        branch: [main, master] # Define uma matriz de branches para executar o job

    steps:
      - uses: actions/checkout@v3 # Ação para clonar o repositório

      - name: Setup Node.js
        uses: actions/setup-node@v2 # Ação para configurar o Node.js
        with:
          node-version: 22.x # Define a versão do Node.js a ser usada (22.x)

      - name: Install dependencies
        run: npm install # Comando para instalar as dependências do projeto

      - name: Run Prettier
        run: npm run prettier-check # Comando para executar o Prettier

      - name: Run Lint
        run: npm run lint # Comando para executar o Lint

      - name: Run Tests
        run: npm test # Comando para executar os testes

      - name: Run Build
        if: github.ref == 'refs/heads/master' && sucess() 
        run: npm run build # Comando para executar o build
